name: Test Apko builds

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v3

      - name: Run build script
        run: ./scripts/build-apko-images.sh

      - name: ghcr.io/defenseunicorns/uds-security-hub built
        run: |
          docker run ghcr.io/defenseunicorns/uds-security-hub-store:latest --help

      - name: ghcr.io/defenseunicorns/uds-security-hub-store built
        run: |
          docker run ghcr.io/defenseunicorns/uds-security-hub-store:latest --help