name: UDS Scan

on:
  schedule:
    # Scheduled to run every day at 2:00 AM UTC / 8:00 PM MT   
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  scan:
<<<<<<< Updated upstream
    runs-on: ubuntu-latest
=======
    runs-on: uds-marketplace-ubuntu-big-boy-8-core
>>>>>>> Stashed changes

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            sum.golang.org:443
            sts.googleapis.com:443
            aquasecurity.github.io:443
            packages.microsoft.com:443
            azure.archive.ubuntu.com:80
            motd.ubuntu.com:443
            esm.ubuntu.com:443
            sqladmin.googleapis.com:443
            34.42.78.208:3307
            ghcr.io:443
            pkg-containers.githubusercontent.com:443
            hooks.slack.com:443  

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v2

      - uses: google-github-actions/auth@62cf5bd3e4211a0a0b51f2c6d6a37129d828611d # v2
        with:
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          project_id: "${{ secrets.GCP_PROJECT }}"

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v2
        with:
          go-version-file: 'go.mod'

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run UDS Scan
        env:
          GHCR_CREDS: ${{ secrets.GHCR_CREDS }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          chmod +x scripts/scan.sh
          ./scripts/scan.sh -f names.txt -v 2
          ./scripts/scan.sh -f leapfrog_names.txt -v 1
